"use client";

import React, { useState } from "react";
import { Search, Sparkles, Rocket, RefreshCw, CheckCircle2, ChevronRight, ShieldAlert } from "lucide-react";

const stages = [
  {
    step: "01",
    phase: "Forensic Audit & Unit Economics",
    icon: Search,
    timeframe: "Days 1 — 5",
    tagline: "Uncovering Hidden Leaks Before Spending A Single Rupee",
    description:
      "Most agencies jump straight into launching random ads. We don't. We perform deep forensic analysis across your Shopify/custom checkout, Google Analytics 4, Meta Pixel events, and contribution margins.",
    bulletPoints: [
      "Full server-side pixel & CAPI event audit (Purchase, AddToCart, ViewContent)",
      "Unit economics stress test: True COGS, CAC tolerance, and breakeven ROAS",
      "Creative fatigue & ad history teardown (identifying what burned money)",
      "Checkout funnel drop-off audit and speed bottleneck identification"
    ],
    outcome: "A clear, ruthless 90-day growth blueprint with non-negotiable KPI targets."
  },
  {
    step: "02",
    phase: "Creative & Hook Production Lab",
    icon: Sparkles,
    timeframe: "Days 6 — 14",
    tagline: "Designing Scroll-Stopping Direct-Response Creative Weapons",
    description:
      "Because Meta and TikTok algorithms prioritize content engagement over bid hacks, your creative IS your targeting. Our creative squad scripts and produces 15-25 high-performing creative hooks.",
    bulletPoints: [
      "Direct-Response UGC video ads with hook rates tested for >40%",
      "3D product animations and dynamic feature callout graphics",
      "Competitor tear-downs to exploit whitespace in ad libraries",
      "Custom landing page mockups designed specifically for the top ad hooks"
    ],
    outcome: "A fresh repository of diverse, high-converting creative angles ready for algorithmic deployment."
  },
  {
    step: "03",
    phase: "Algorithmic Media Architecture",
    icon: Rocket,
    timeframe: "Days 15 — 30",
    tagline: "Deploying Multi-Channel Acquisition Across Meta, Google & TikTok",
    description:
      "We build resilient, bulletproof account architectures designed to withstand platform volatility. We leverage broad targeting, Advantage+ Shopping Campaigns (ASC+), and Google Performance Max with bid caps.",
    bulletPoints: [
      "Dynamic testing sandbox campaign structure to isolate winning hooks",
      "High-intent Google Search capture to harvest warm demand generated by Meta",
      "Cost-cap and minimum-ROAS bid constraints to protect ad spend profitability",
      "Real-time contribution margin tracking via sGTM"
    ],
    outcome: "Consistent, profitable volume scaling while maintaining or lowering customer acquisition costs."
  },
  {
    step: "04",
    phase: "Retention Loops & Compounding Scale",
    icon: RefreshCw,
    timeframe: "Days 30 — 90+",
    tagline: "Maximizing Customer Lifetime Value & Net Bottom-Line Profit",
    description:
      "Scaling isn't just top-of-funnel ad spend. It's turning 1-time buyers into 3-time loyalists. We implement automated WhatsApp conversational flows, VIP SMS broadcasts, and Klaviyo loyalty loops.",
    bulletPoints: [
      "Automated WhatsApp sequences for abandoned carts, COD confirmations & VIP drops",
      "Replenishment reminders timed to product consumption cycles",
      "Continuous A/B testing on bundles, free-shipping thresholds, and cart drawer upsells",
      "Weekly growth sprint calls with live executive dashboards"
    ],
    outcome: "30-50% bump in customer LTV, maximizing profit extracted from every ad dollar."
  }
];

export default function GrowthEngine() {
  const [activeStep, setActiveStep] = useState(0);
  const currentStage = stages[activeStep];
  const StepIcon = currentStage.icon;

  return (
    <section id="engine" className="py-20 md:py-28 relative bg-white dark:bg-[#0B0F1A] border-t border-slate-200/80 dark:border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="max-w-3xl mx-auto text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-50 dark:bg-brand-950/70 border border-brand-200 dark:border-brand-800 text-brand-700 dark:text-brand-300 text-xs font-bold uppercase tracking-wider">
            Proprietary Framework
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-display font-extrabold text-slate-900 dark:text-white tracking-tight">
            The <span className="gradient-text">CF Growth Engine™</span>
          </h2>
          <p className="text-base sm:text-lg text-slate-600 dark:text-slate-300">
            A 4-stage systematic methodology that turns chaotic digital ad spend into an engineered, predictable revenue machine.
          </p>
        </div>

        {/* Step Buttons Bar */}
        <div className="mt-12 grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4">
          {stages.map((st, index) => {
            const isCurrent = activeStep === index;
            const Icon = st.icon;
            return (
              <button
                key={st.step}
                onClick={() => setActiveStep(index)}
                className={`p-4 rounded-xl border text-left transition-all duration-200 flex flex-col justify-between ${
                  isCurrent
                    ? "bg-brand-600 text-white border-brand-600 shadow-lg shadow-brand-500/25 scale-[1.02]"
                    : "bg-slate-50 dark:bg-slate-900/60 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-800 hover:border-brand-300 dark:hover:border-brand-800"
                }`}
              >
                <div className="flex items-center justify-between w-full mb-3">
                  <span className={`text-xl font-display font-black ${isCurrent ? "text-brand-200" : "text-brand-600 dark:text-brand-400"}`}>
                    {st.step}
                  </span>
                  <div className={`p-2 rounded-lg ${isCurrent ? "bg-white/20 text-white" : "bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300"}`}>
                    <Icon className="w-4 h-4" />
                  </div>
                </div>
                <div>
                  <div className={`text-xs font-semibold uppercase tracking-wider ${isCurrent ? "text-brand-200" : "text-slate-400 dark:text-slate-500"}`}>
                    {st.timeframe}
                  </div>
                  <div className={`font-display font-bold text-sm sm:text-base mt-0.5 line-clamp-1 ${isCurrent ? "text-white" : "text-slate-900 dark:text-white"}`}>
                    {st.phase}
                  </div>
                </div>
              </button>
            );
          })}
        </div>

        {/* Active Stage Detailed Card */}
        <div className="mt-8 bg-slate-50 dark:bg-slate-900 rounded-3xl p-6 sm:p-10 border border-slate-200 dark:border-slate-800 shadow-xl relative overflow-hidden">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            
            <div className="lg:col-span-7 space-y-6">
              <div className="flex items-center gap-3">
                <span className="text-3xl font-display font-black text-brand-600 dark:text-brand-400">
                  Stage {currentStage.step}
                </span>
                <span className="text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-brand-100 dark:bg-brand-950 text-brand-700 dark:text-brand-300 border border-brand-200 dark:border-brand-800">
                  {currentStage.timeframe}
                </span>
              </div>

              <div>
                <h3 className="text-2xl sm:text-3xl font-display font-extrabold text-slate-900 dark:text-white">
                  {currentStage.tagline}
                </h3>
                <p className="text-sm sm:text-base text-slate-600 dark:text-slate-300 mt-2 leading-relaxed">
                  {currentStage.description}
                </p>
              </div>

              {/* Bullet Points */}
              <div className="space-y-3 pt-2">
                <div className="text-xs font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                  Stage Deliverables & Milestones:
                </div>
                {currentStage.bulletPoints.map((pt, idx) => (
                  <div key={idx} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-200">
                    <CheckCircle2 className="w-5 h-5 text-brand-600 dark:text-brand-400 shrink-0 mt-0.5" />
                    <span>{pt}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Card / Outcome highlight */}
            <div className="lg:col-span-5 bg-white dark:bg-slate-950/80 rounded-2xl p-6 sm:p-7 border border-slate-200 dark:border-slate-800/80 shadow-md space-y-5">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-brand-50 dark:bg-brand-950 text-brand-600 dark:text-brand-400 border border-brand-200 dark:border-brand-800">
                  <StepIcon className="w-6 h-6" />
                </div>
                <div>
                  <span className="text-xs text-slate-400 uppercase tracking-wider block font-semibold">Phase Focus</span>
                  <h4 className="font-display font-bold text-base text-slate-900 dark:text-white">{currentStage.phase}</h4>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900/60 border border-slate-200/80 dark:border-slate-800 space-y-1.5">
                <span className="text-xs font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5" /> Guaranteed Stage Outcome
                </span>
                <p className="text-sm font-medium text-slate-800 dark:text-slate-200">
                  &ldquo;{currentStage.outcome}&rdquo;
                </p>
              </div>

              <div className="pt-2">
                <a
                  href="#audit-form"
                  className="w-full inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-brand-600 hover:bg-brand-500 text-white text-sm font-semibold shadow-md transition-all"
                >
                  <span>Apply This Engine to Your Brand</span>
                  <ChevronRight className="w-4 h-4" />
                </a>
              </div>
            </div>

          </div>
        </div>

      </div>
    </section>
  );
}
